
-- Esquemas iniciales
CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    email VARCHAR(160) NOT NULL UNIQUE,
    password VARCHAR(120) NOT NULL
);

CREATE TABLE IF NOT EXISTS libros (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isbn VARCHAR(30) NOT NULL UNIQUE,
    titulo VARCHAR(180) NOT NULL,
    autor VARCHAR(160) NOT NULL,
    stock INT NOT NULL CHECK (stock >= 0)
);

CREATE TABLE IF NOT EXISTS prestamos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    libro_id BIGINT NOT NULL,
    titulo_libro VARCHAR(180) NOT NULL, 
    isbn_libro  VARCHAR(30) NOT NULL,
    fecha_prestamo DATE NOT NULL,
    fecha_devolucion DATE NULL,
    devuelto BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);

-- Insertar usuario de prueba
INSERT INTO usuarios (id, nombre, email, password) 
VALUES (1,'Admin', 'admin@untec.cl', 'untec2026'),
(104900,'Lucho', 'lucho@untec.cl', 'untec2026'),
(245980, 'Katulo', 'katulo@untec.cl', 'untec2026');

-- Insertar libros de prueba
INSERT INTO libros (isbn, titulo, autor, stock)
VALUES ( '978-1-394-28924-0', 'Java For Dummies, 9th edition', 'Barry Burd', 2),
('978-0-201-63361-0', 'Design Patterns: Elements of Reusable Object-Oriented Software', 'Erich Gamma et al', 2),
('978-1-770-41175-3', 'The Death of WCW', 'R.Reynolds & B.Alvarez', 2),
('978-1-482-92632-3', 'At the Mountains of Madness', 'H.P.Lovecraft', 2);

-- Insertar préstamos de prueba
INSERT INTO prestamos (usuario_id, libro_id, titulo_libro, isbn_libro, fecha_prestamo, fecha_devolucion, devuelto)
VALUES 
    (245980, 1, 'Java For Dummies, 9th edition', '978-1-394-28924-0', '2026-08-11', NULL, FALSE),
    (245980, 4, 'At the Mountains of Madness', '978-1-482-92632-3', CURRENT_DATE - 5, CURRENT_DATE - 1, TRUE),
    (104900, 2, 'Design Patterns: Elements of Reusable Object-Oriented Software', '978-0-201-63361-0', CURRENT_DATE - 10, NULL, FALSE);

